export enum Coll {
    CATEGORY = "categories",
    SUBCATEGORY = "subcategories",
    USER = "users",
    ADMIN = "admins",
    LANCER = "lancers",
    REFERRAL = "referrals",
    SELLER_INFO = "sellerInfo",
    SERVICES = "services",
    CHAT = "chats",
    MESSAGE = "messages",
    ORDER = "orders",
    TRANSACTION = "transactions",
    SAVE_LIST = "saveLists",
    REVIEWS = "reviews",
}
